### ISSUE TITLE
x64 server

### ISSUE THREAD

**Issue by HeartBurzum** [eqdialup/MySEQ#10]
I completed the work for the server to work with the 64 bit eqgame.exe and all the current test offsets in my repo, I would post it to the myseq forums but registration is broken still.

You can find it here [myseq x64](https://github.com/HeartBurzum/myseq)

**Comment by eqdialup** [comment]
Sweet. And much cleaner than what I had so far. Do you have any privacy issues with me pulling this in as is? I don't want to add you to the repository if you don't want in.

 
 

Sent: Wednesday, January 19, 2022 at 4:30 AM
From: "HeartBurzum" ***@***.***>
To: "eqdialup/MySEQ" ***@***.***>
Cc: "Subscribed" ***@***.***>
Subject: [eqdialup/MySEQ] x64 server (Issue #10)


 

I completed the work for the server to work with the 64 bit eqgame.exe and all the current test offsets in my repo, I would post it to the myseq forums but registration is broken still.

You can find it here myseq x64

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HeartBurzum** [comment]
> Sweet. And much cleaner than what I had so far. Do you have any privacy issues with me pulling this in as is? I don't want to add you to the repository if you don't want in.

I have no issues with you merging.

**Comment by eqdialup** [comment]
Good deal. I just wanted to make sure there were no stray comits with a real email address etc. I have meetings in the morning, but after that I'll pull into my hidden 64bit branch, test it, and open it up. I was going through and converting everything to _ptr instead of q vs d. Yours is much cleaner.

 
 

Sent: Wednesday, January 19, 2022 at 8:51 PM

**Comment by HeartBurzum** [comment]
I went ahead and did a pull request so its less work for you to deal with and cleaner. 
#11 64bit PR

**Comment by barecode** [comment]
You guys are doing god's work.

**Comment by eqdialup** [comment]
Merged. Looks great. Took me a second to remember how to fix differences in our build setups, but once it compiled it works perfectly.

**Comment by HeartBurzum** [comment]
I'll have a few more PRs coming down in a few days once I have time.
